-- SACE_db - DDL del esquema completo (SIN datos). Generado con pg_dump --schema-only.
-- Evidencia academica rubrica 4 (Base de datos). El backend tambien crea estas tablas
-- automaticamente con ddl-auto=update y DataInitializer siembra los datos iniciales.

--
-- PostgreSQL database dump
--

\restrict VC9zKMJLbJaRWnxERp6LtuIqcgrRlffdTcHOPQZUDLESKuPImmw6GbTpCoYVAGT

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: chatbot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chatbot (
    id bigint NOT NULL,
    estado_operativo character varying(255),
    nombre character varying(255),
    version character varying(255),
    CONSTRAINT chatbot_estado_operativo_check CHECK (((estado_operativo)::text = ANY ((ARRAY['ACTIVO'::character varying, 'INACTIVO'::character varying, 'MANTENIMIENTO'::character varying])::text[])))
);


--
-- Name: chatbot_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chatbot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chatbot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chatbot_pregunta_frecuente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chatbot_pregunta_frecuente (
    chatbot_id bigint NOT NULL,
    pregunta_frecuente_id bigint NOT NULL
);


--
-- Name: cliente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cliente (
    historial_consultas character varying(255),
    preferencias_comunicacion character varying(255),
    id bigint NOT NULL
);


--
-- Name: cliente_servicio; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cliente_servicio (
    cliente_id bigint NOT NULL,
    servicio_id bigint NOT NULL
);


--
-- Name: empleado; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.empleado (
    cargo_especifico character varying(255),
    departamento character varying(255),
    estado_disponibilidad character varying(255),
    id bigint NOT NULL,
    CONSTRAINT empleado_estado_disponibilidad_check CHECK (((estado_disponibilidad)::text = ANY ((ARRAY['DISPONIBLE'::character varying, 'OCUPADO'::character varying, 'EN_PAUSA'::character varying, 'FUERA_DE_TURNO'::character varying])::text[])))
);


--
-- Name: mensaje; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mensaje (
    id bigint NOT NULL,
    calificacion integer,
    comentario_satisfaccion character varying(255),
    contenido character varying(255),
    fecha timestamp(6) without time zone,
    nombre_archivo character varying(255),
    remitente character varying(255),
    ruta_archivo character varying(255),
    tipo character varying(255),
    solicitud_id bigint,
    CONSTRAINT mensaje_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['TEXTO'::character varying, 'ARCHIVO'::character varying, 'SISTEMA'::character varying])::text[])))
);


--
-- Name: mensaje_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mensaje ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensaje_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pago; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pago (
    id_pago bigint NOT NULL,
    correo_notificado boolean NOT NULL,
    estado character varying(255) NOT NULL,
    fecha_pago timestamp(6) without time zone NOT NULL,
    llave_destino character varying(255) NOT NULL,
    metodo_pago character varying(255) NOT NULL,
    monto numeric(12,2) NOT NULL,
    url_pdf character varying(255),
    id_cliente bigint NOT NULL,
    id_solicitud bigint NOT NULL
);


--
-- Name: pago_id_pago_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pago ALTER COLUMN id_pago ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pago_id_pago_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persona; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.persona (
    tipo_persona_discriminador character varying(31) NOT NULL,
    id bigint NOT NULL,
    apellido character varying(255),
    contrasenia character varying(255),
    email character varying(255),
    estado_acceso character varying(255),
    nombre character varying(255),
    numero_documento character varying(255),
    telefono character varying(255),
    tipo_documento character varying(255),
    tipo_usuario character varying(255),
    CONSTRAINT persona_estado_acceso_check CHECK (((estado_acceso)::text = ANY ((ARRAY['ACTIVA'::character varying, 'INACTIVA'::character varying, 'BLOQUEADA'::character varying])::text[]))),
    CONSTRAINT persona_tipo_documento_check CHECK (((tipo_documento)::text = ANY ((ARRAY['CC'::character varying, 'CE'::character varying, 'PASAPORTE'::character varying, 'OTRO'::character varying])::text[]))),
    CONSTRAINT persona_tipo_persona_discriminador_check CHECK (((tipo_persona_discriminador)::text = ANY ((ARRAY['Persona'::character varying, 'Cliente'::character varying, 'Empleado'::character varying])::text[]))),
    CONSTRAINT persona_tipo_usuario_check CHECK (((tipo_usuario)::text = ANY ((ARRAY['CLIENTE'::character varying, 'ASESOR_VIAJES'::character varying, 'COORDINADOR_DESTINO'::character varying, 'ADMINISTRADOR'::character varying])::text[])))
);


--
-- Name: persona_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.persona ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pregunta_frecuente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pregunta_frecuente (
    id bigint NOT NULL,
    categoria character varying(255),
    palabras_clave character varying(255),
    pregunta character varying(255),
    respuesta character varying(255)
);


--
-- Name: pregunta_frecuente_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pregunta_frecuente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pregunta_frecuente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: servicio; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.servicio (
    id bigint NOT NULL,
    descripcion character varying(255),
    destino character varying(255),
    duracion character varying(255),
    nombre character varying(255),
    precio numeric(19,2),
    tipo_servicio character varying(255),
    CONSTRAINT servicio_tipo_servicio_check CHECK (((tipo_servicio)::text = ANY ((ARRAY['PAQUETE_TODO_INCLUIDO'::character varying, 'SOLO_HOTEL'::character varying, 'VUELO_HOTEL'::character varying, 'TOUR_EXCURSION'::character varying, 'PASADIA'::character varying, 'ASISTENCIA_MEDICA'::character varying, 'OTRO'::character varying])::text[])))
);


--
-- Name: servicio_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.servicio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.servicio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solicitud; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solicitud (
    id bigint NOT NULL,
    asunto character varying(255),
    categoria character varying(255),
    descripcion character varying(255),
    estado character varying(255),
    fecha_creacion timestamp(6) without time zone,
    prioridad character varying(255),
    titulo character varying(255),
    chatbot_asignado_id bigint,
    cliente_id bigint,
    empleado_asignado_id bigint,
    servicio_generado_id bigint,
    CONSTRAINT solicitud_estado_check CHECK (((estado)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'EN_PROCESO'::character varying, 'RESUELTA'::character varying, 'CANCELADA'::character varying])::text[]))),
    CONSTRAINT solicitud_prioridad_check CHECK (((prioridad)::text = ANY ((ARRAY['BAJA'::character varying, 'MEDIA'::character varying, 'ALTA'::character varying, 'URGENTE'::character varying])::text[])))
);


--
-- Name: solicitud_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.solicitud ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solicitud_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chatbot chatbot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chatbot
    ADD CONSTRAINT chatbot_pkey PRIMARY KEY (id);


--
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);


--
-- Name: empleado empleado_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.empleado
    ADD CONSTRAINT empleado_pkey PRIMARY KEY (id);


--
-- Name: mensaje mensaje_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mensaje
    ADD CONSTRAINT mensaje_pkey PRIMARY KEY (id);


--
-- Name: pago pago_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pago
    ADD CONSTRAINT pago_pkey PRIMARY KEY (id_pago);


--
-- Name: persona persona_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_pkey PRIMARY KEY (id);


--
-- Name: pregunta_frecuente pregunta_frecuente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pregunta_frecuente
    ADD CONSTRAINT pregunta_frecuente_pkey PRIMARY KEY (id);


--
-- Name: servicio servicio_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.servicio
    ADD CONSTRAINT servicio_pkey PRIMARY KEY (id);


--
-- Name: solicitud solicitud_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitud
    ADD CONSTRAINT solicitud_pkey PRIMARY KEY (id);


--
-- Name: pago fk2fmwlqws6jmrycdhkn2bl8m0p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pago
    ADD CONSTRAINT fk2fmwlqws6jmrycdhkn2bl8m0p FOREIGN KEY (id_cliente) REFERENCES public.cliente(id);


--
-- Name: cliente_servicio fk6aaxox7romwphrqopb8gvkxkp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente_servicio
    ADD CONSTRAINT fk6aaxox7romwphrqopb8gvkxkp FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);


--
-- Name: chatbot_pregunta_frecuente fk6wu8o3nwb8fqsorf8pbeq4xog; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chatbot_pregunta_frecuente
    ADD CONSTRAINT fk6wu8o3nwb8fqsorf8pbeq4xog FOREIGN KEY (chatbot_id) REFERENCES public.chatbot(id);


--
-- Name: cliente_servicio fk7kg20la1tug6t8au3drpk6duh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente_servicio
    ADD CONSTRAINT fk7kg20la1tug6t8au3drpk6duh FOREIGN KEY (servicio_id) REFERENCES public.servicio(id);


--
-- Name: solicitud fkbwy4fy0oaswyxsbfeeghrk47l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitud
    ADD CONSTRAINT fkbwy4fy0oaswyxsbfeeghrk47l FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);


--
-- Name: solicitud fkfyw59qtb8sxrwidefuyysyuc1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitud
    ADD CONSTRAINT fkfyw59qtb8sxrwidefuyysyuc1 FOREIGN KEY (empleado_asignado_id) REFERENCES public.empleado(id);


--
-- Name: pago fkh0ust5eklpc5crt8sre2ymtkr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pago
    ADD CONSTRAINT fkh0ust5eklpc5crt8sre2ymtkr FOREIGN KEY (id_solicitud) REFERENCES public.solicitud(id);


--
-- Name: cliente fkkpvkbjg32bso6riqge70hwcel; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT fkkpvkbjg32bso6riqge70hwcel FOREIGN KEY (id) REFERENCES public.persona(id);


--
-- Name: empleado fkl6nu1s893o9x7pmxo0wdhfiei; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.empleado
    ADD CONSTRAINT fkl6nu1s893o9x7pmxo0wdhfiei FOREIGN KEY (id) REFERENCES public.persona(id);


--
-- Name: solicitud fkm4dkub6km0un1t4siubqenwa1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitud
    ADD CONSTRAINT fkm4dkub6km0un1t4siubqenwa1 FOREIGN KEY (chatbot_asignado_id) REFERENCES public.chatbot(id);


--
-- Name: solicitud fkmi5h9sv4g6ok9vj0bkyftxsx2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitud
    ADD CONSTRAINT fkmi5h9sv4g6ok9vj0bkyftxsx2 FOREIGN KEY (servicio_generado_id) REFERENCES public.servicio(id);


--
-- Name: chatbot_pregunta_frecuente fkmii0k409a8kcpfycbvmt0aqiy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chatbot_pregunta_frecuente
    ADD CONSTRAINT fkmii0k409a8kcpfycbvmt0aqiy FOREIGN KEY (pregunta_frecuente_id) REFERENCES public.pregunta_frecuente(id);


--
-- Name: mensaje fkplnpb5enlobqnse3y7wbwvdx9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mensaje
    ADD CONSTRAINT fkplnpb5enlobqnse3y7wbwvdx9 FOREIGN KEY (solicitud_id) REFERENCES public.solicitud(id);


--
-- PostgreSQL database dump complete
--

\unrestrict VC9zKMJLbJaRWnxERp6LtuIqcgrRlffdTcHOPQZUDLESKuPImmw6GbTpCoYVAGT

